-- 题目 计算用户的平均次日留存率
-- 关键字 必会的常用函数 日期函数
-- 思路，
-- 获取第一天上线人数
-- 获取第二天上线人数
TODO: NOT SUCCESS -- SELECT
--   device_id,
--   EXTRACT(
--     MONTH
--     FROM
--       date
--   ) AS month,
--   EXTRACT(
--     DAY
--     FROM
--       date
--   ) AS day
-- FROM
--   (
--     SELECT
--       device_id,
--       EXTRACT(
--         MONTH
--         FROM
--           date
--       ) AS month,
--       EXTRACT(
--         DAY
--         FROM
--           date
--       ) AS day
--     FROM
--       Question_practice_detail
--   )
